---
- name: update and install git 
  hosts: node1
  become: true
  gather_facts: no
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
    - name: install 7z
      apt:
        name: p7zip-full
        state: present
      with_items:
        - p7zip-full