---
- name: update and install git 
  hosts: node2
  become: true
  gather_facts: no
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
    - name: install git
      apt:
        name: git
        state: present